In [12]:
#practise pytorch
#Tensor, (vector for 1 D, matrix for 2D,.... )
from __future__ import print_function
import torch as t
import numpy as np
# 构建 5*3 矩阵, 只是分配空间，未初始化
x = t.Tensor(5, 3)
x


tensor([[9.1834e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.2948e-42, 0.0000e+00],
        [0.0000e+00, 3.5063e-01, 0.0000e+00]])

In [13]:
# 使用[0, 1]均匀分布随机初始化二维数组
x = t.rand(5, 3)
x

tensor([[0.8415, 0.7503, 0.4877],
        [0.0555, 0.3417, 0.2958],
        [0.5302, 0.0972, 0.9777],
        [0.6870, 0.9510, 0.7671],
        [0.7909, 0.0477, 0.4079]])

In [3]:
print(x.size())
x.size()[0], x.size(1)

torch.Size([5, 3])


(5, 3)

In [4]:
# torch.Size 是tuple对象的子类
y = t.rand(5, 3)
y

tensor([[0.5937, 0.4054, 0.7339],
        [0.1190, 0.9442, 0.5900],
        [0.2999, 0.3771, 0.4538],
        [0.9195, 0.7883, 0.9799],
        [0.5684, 0.2640, 0.5995]])

In [5]:
x + y

tensor([[0.6646, 0.9130, 1.4874],
        [0.1410, 1.1279, 0.9993],
        [0.5938, 0.5116, 0.7039],
        [1.8269, 0.9613, 1.0165],
        [1.4339, 0.3506, 1.0142]])

In [6]:
t.add(x, y)

tensor([[0.6646, 0.9130, 1.4874],
        [0.1410, 1.1279, 0.9993],
        [0.5938, 0.5116, 0.7039],
        [1.8269, 0.9613, 1.0165],
        [1.4339, 0.3506, 1.0142]])

In [7]:
z = t.add(x, y)

In [8]:
z

tensor([[0.6646, 0.9130, 1.4874],
        [0.1410, 1.1279, 0.9993],
        [0.5938, 0.5116, 0.7039],
        [1.8269, 0.9613, 1.0165],
        [1.4339, 0.3506, 1.0142]])

In [9]:
x.add(y)

tensor([[0.6646, 0.9130, 1.4874],
        [0.1410, 1.1279, 0.9993],
        [0.5938, 0.5116, 0.7039],
        [1.8269, 0.9613, 1.0165],
        [1.4339, 0.3506, 1.0142]])

In [10]:
x.add_(y)

tensor([[0.6646, 0.9130, 1.4874],
        [0.1410, 1.1279, 0.9993],
        [0.5938, 0.5116, 0.7039],
        [1.8269, 0.9613, 1.0165],
        [1.4339, 0.3506, 1.0142]])

In [11]:
x.numpy()

array([[0.66461754, 0.9129718 , 1.4874167 ],
       [0.14098221, 1.1279081 , 0.99933726],
       [0.5937922 , 0.5116101 , 0.7039032 ],
       [1.8268785 , 0.9612763 , 1.0165431 ],
       [1.4339447 , 0.35062873, 1.0142499 ]], dtype=float32)

In [1]:
import numpy as np

def cross_entropy(Y, P):
    Y = np.float_(Y)
    P = np.float_(P)
    return -np.sum(Y * np.log(P) + (1 - Y) * np.log(1 - P))

In [2]:
import numpy as np

# Write a function that takes as input a list of numbers, and returns
# the list of values given by the softmax function.
def softmax(L):
    norm_L = np.exp(L)
    norm_L = np.divide(norm_L, norm_L.sum())
    
    return norm_L

In [7]:
correct = 70
total =120
accuracy = 100 * correct / total
print("Accuracy: [%d / %d] = %.4f \n"
      % (correct,total,accuracy))

Accuracy: [70 / 120] = 58.3333 

