In [8]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [1 2 3 4 5]
x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [5]:
np.linspace(2, 32, 16, endpoint=False)

array([ 2.   ,  3.875,  5.75 ,  7.625,  9.5  , 11.375, 13.25 , 15.125,
       17.   , 18.875, 20.75 , 22.625, 24.5  , 26.375, 28.25 , 30.125])

In [6]:
np.linspace(2, 32, 16, 2)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
       28., 30., 32.])

In [7]:
np.linspace(2, 32, 16, 2).reshape(4,4)

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.],
       [18., 20., 22., 24.],
       [26., 28., 30., 32.]])

In [8]:
x = np.array([1, 2, 3, 4, 5])

In [9]:
print(x)

[1 2 3 4 5]


In [11]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x)
x[0,0] = 10
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
y = np.delete(x, 0, axis = 0)
print(y)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
y = np.delete(y, [1,2], axis = 1)
print(y)

[[ 4]
 [ 7]
 [10]]


In [18]:
z = np.append(y,[[5,8,11],[6,9,12],[3,5,9]],axis=1)
print(z)

[[ 4  5  8 11]
 [ 7  6  9 12]
 [10  3  5  9]]


In [19]:
z1 = np.append(z,[[5,8,11,22],[6,9,12,44],[3,5,9,90]],axis=0)
print(z1)

[[ 4  5  8 11]
 [ 7  6  9 12]
 [10  3  5  9]
 [ 5  8 11 22]
 [ 6  9 12 44]
 [ 3  5  9 90]]


In [20]:
z2 = np.insert(z1, 1,10, axis = 1)
print(z2)

[[ 4 10  5  8 11]
 [ 7 10  6  9 12]
 [10 10  3  5  9]
 [ 5 10  8 11 22]
 [ 6 10  9 12 44]
 [ 3 10  5  9 90]]


In [21]:
z3 = np.insert(z2, 1, [2,3,4,5,6], axis=0)
print(z3)

[[ 4 10  5  8 11]
 [ 2  3  4  5  6]
 [ 7 10  6  9 12]
 [10 10  3  5  9]
 [ 5 10  8 11 22]
 [ 6 10  9 12 44]
 [ 3 10  5  9 90]]


In [23]:
z4 = np.vstack((z2, z3))
print(z4)

[[ 4 10  5  8 11]
 [ 7 10  6  9 12]
 [10 10  3  5  9]
 [ 5 10  8 11 22]
 [ 6 10  9 12 44]
 [ 3 10  5  9 90]
 [ 4 10  5  8 11]
 [ 2  3  4  5  6]
 [ 7 10  6  9 12]
 [10 10  3  5  9]
 [ 5 10  8 11 22]
 [ 6 10  9 12 44]
 [ 3 10  5  9 90]]


In [24]:
z5 = np.hstack((z2,z2))
print(z5)

[[ 4 10  5  8 11  4 10  5  8 11]
 [ 7 10  6  9 12  7 10  6  9 12]
 [10 10  3  5  9 10 10  3  5  9]
 [ 5 10  8 11 22  5 10  8 11 22]
 [ 6 10  9 12 44  6 10  9 12 44]
 [ 3 10  5  9 90  3 10  5  9 90]]


In [30]:
x = np.arange(20).reshape(4,5)
print(x)
print(x[1:4, 2:5])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [36]:
y = x[:,2:].copy()
print(y)

[[ 2  3  4]
 [ 7  8  9]
 [20 13 14]
 [17 18 19]]


In [38]:
x[2,2] = 30
print(y)

[[ 2  3  4]
 [ 7  8  9]
 [20 13 14]
 [17 18 19]]


In [40]:
diag = np.diag(y)
print(diag)

[ 2  8 14]


In [41]:
print(np.diag(y, k =1))
print(np.diag(y, k =2))
print(np.diag(y, k =-1))
print(np.diag(y, k =-2))


[3 9]
[4]
[ 7 13 19]
[20 18]


In [42]:
print(np.unique(y))

[ 2  3  4  7  8  9 13 14 17 18 19 20]


In [50]:
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([6,7,8,9]).reshape(2,2)
print("X + Y = \n", X + Y)
print("X - Y = \n", X - Y)
print("X * Y = \n", X * Y)
print("X / Y = \n", X / Y)

print("Exp(X) = \n", np.exp(X))
print("SQRT(X) = \n", np.sqrt(X))
print("POW(X) = \n", np.power(X, 2))




X + Y = 
 [[ 7  9]
 [11 13]]
X - Y = 
 [[-5 -5]
 [-5 -5]]
X * Y = 
 [[ 6 14]
 [24 36]]
X / Y = 
 [[0.16666667 0.28571429]
 [0.375      0.44444444]]
Exp(X) = 
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
SQRT(X) = 
 [[1.         1.41421356]
 [1.73205081 2.        ]]
POW(X) = 
 [[ 1  4]
 [ 9 16]]


In [51]:
print("X = \n", X)

print("max(X) = \n", np.max(X))
print("max(X) axis =0 \n", np.max(X, axis = 0))
print("max(X) axis =1 \n", np.max(X, axis = 1))

print("min(X) = \n", np.min(X))
print("min(X) axis =0 \n", np.min(X, axis = 0))
print("min(X) axis =1 \n", np.min(X, axis = 1))

print("sum(X) = \n", np.sum(X))
print("sum(X) axis =0 \n", np.sum(X, axis = 0))
print("sum(X) axis =1 \n", np.sum(X, axis = 1))


X = 
 [[1 2]
 [3 4]]
max(X) = 
 4
max(X) axis =0 
 [3 4]
max(X) axis =1 
 [2 4]
min(X) = 
 1
min(X) axis =0 
 [1 2]
min(X) axis =1 
 [1 3]
sum(X) = 
 10
sum(X) axis =0 
 [4 6]
sum(X) axis =1 
 [3 7]


In [52]:
print("X = \n", X)

print("mean(X) = \n", np.mean(X))
print("mean(X) axis =0 \n", np.mean(X, axis = 0))
print("mean(X) axis =1 \n", np.mean(X, axis = 1))

print("median(X) = \n", np.median(X))
print("median(X) axis =0 \n", np.median(X, axis = 0))
print("median(X) axis =1 \n", np.median(X, axis = 1))



print("std(X) = \n", np.std(X))
print("std(X) axis =0 \n", np.std(X, axis = 0))
print("std(X) axis =1 \n", np.std(X, axis = 1))

X = 
 [[1 2]
 [3 4]]
mean(X) = 
 2.5
mean(X) axis =0 
 [2. 3.]
mean(X) axis =1 
 [1.5 3.5]
median(X) = 
 2.5
median(X) axis =0 
 [2. 3.]
median(X) axis =1 
 [1.5 3.5]
std(X) = 
 1.118033988749895
std(X) axis =0 
 [1. 1.]
std(X) axis =1 
 [0.5 0.5]


In [4]:
import pandas as pd

groceries = pd.Series(data = [30, 6, 'Yes', 'No'], index = ['eggs', 'apples', 'milk', 'bread'])

print(groceries)
print("groceries shape = ", groceries.shape)
print("groceries dimension = ", groceries.ndim)
print("groceries size = ", groceries.size, "elements")

print("groceries values = ", groceries.values)
print("groceries indices = ", groceries.index)

print("Is 'banana' in groceries = ", 'banban' in groceries)
print("Is 'bread' in groceries = ", 'bread' in groceries)

eggs       30
apples      6
milk      Yes
bread      No
dtype: object
groceries shape =  (4,)
groceries dimension =  1
groceries size =  4 elements
groceries values =  [30 6 'Yes' 'No']
groceries indices =  Index(['eggs', 'apples', 'milk', 'bread'], dtype='object')
Is 'banana' in groceries =  False
Is 'bread' in groceries =  True


In [5]:
# 练习 pandas series， 处理一维数据

fruits = pd.Series(data=[1,2,3], index=['apple', 'banana', 'grape'])
print(fruits)

apple     1
banana    2
grape     3
dtype: int64


In [9]:
print("fruits + 2 = \n", fruits + 2)
print("fruits - 3 = \n",fruits - 3)
print("fruits / 2 = \n",fruits / 2)
print("fruits * 2 = \n",fruits * 2)
print("fruits ** 2 = \n",fruits ** 2)
print(" EXP(fruits) = \n", np.exp(fruits))
print(" POWER(fruits, 2) = \n", np.power(fruits, 2))
print(" SQRT(fruits) = \n", np.sqrt(fruits))


fruits + 2 = 
 apple     3
banana    4
grape     5
dtype: int64
fruits - 3 = 
 apple    -2
banana   -1
grape     0
dtype: int64
fruits / 2 = 
 apple     0.5
banana    1.0
grape     1.5
dtype: float64
fruits * 2 = 
 apple     2
banana    4
grape     6
dtype: int64
fruits ** 2 = 
 apple     1
banana    4
grape     9
dtype: int64
 EXP(fruits) = 
 apple      2.718282
banana     7.389056
grape     20.085537
dtype: float64
 POWER(fruits, 2) = 
 apple     1
banana    4
grape     9
dtype: int64
 SQRT(fruits) = 
 apple     1.000000
banana    1.414214
grape     1.732051
dtype: float64


In [11]:
import pandas as pd

# Create a Pandas Series that contains the distance of some planets from the Sun.
# Use the name of the planets as the index to your Pandas Series, and the distance
# from the Sun as your data. The distance from the Sun is in units of 10^6 km

distance_from_sun = [149.6, 1433.5, 227.9, 108.2, 778.6]

planets = ['Earth','Saturn', 'Mars','Venus', 'Jupiter']

# Create a Pandas Series using the above data, with the name of the planets as
# the index and the distance from the Sun as your data.
dist_planets = pd.Series(data=distance_from_sun, index = planets)

# Calculate the number of minutes it takes sunlight to reach each planet. You can
# do this by dividing the distance from the Sun for each planet by the speed of light.
# Since in the data above the distance from the Sun is in units of 10^6 km, you can
# use a value for the speed of light of c = 18, since light travels 18 x 10^6 km/minute.
time_light = dist_planets / 18

# Use Boolean indexing to select only those planets for which sunlight takes less
# than 40 minutes to reach them.
close_planets = time_light[time_light<=40]

print("dist_planets = \n", dist_planets)
print("time_light = \n", time_light)
print("close_planets = \n", close_planets)

dist_planets = 
 Earth       149.6
Saturn     1433.5
Mars        227.9
Venus       108.2
Jupiter     778.6
dtype: float64
time_light = 
 Earth       8.311111
Saturn     79.638889
Mars       12.661111
Venus       6.011111
Jupiter    43.255556
dtype: float64
close_planets = 
 Earth     8.311111
Mars     12.661111
Venus     6.011111
dtype: float64


In [23]:
# 练习Pandas DataFrame，专门处理二维数据，类似Excel,
# 注意比较Numpy narray方法

items = {'Bob' : pd.Series(data = [245, 25, 55], index = ['bike', 'pants', 'watch']),
         'Alice' : pd.Series(data = [40, 110, 500, 45], index = ['book', 'glasses', 'bike', 'pants'])}
dataframe = pd.DataFrame(items, index=['bike'], columns = ['Bob'])
print(dataframe)

print("shape = \n", dataframe.shape)
print("dimension \n", dataframe.ndim)
print("total elements \n", dataframe.size)
print("row index \n", dataframe.index)
print("list each elements \n", dataframe.values)
print("column index \n", dataframe.columns)

      Bob
bike  245
shape = 
 (1, 1)
dimension 
 2
total elements 
 1
row index 
 Index(['bike'], dtype='object')
list each elements 
 [[245]]
column index 
 Index(['Bob'], dtype='object')


In [18]:
data = {'Bob': pd.Series(data=[1,2,3,6]),
        'Alice': pd.Series(data=[5,6,7])}
dataframe = pd.DataFrame(data)
print(dataframe)

print("shape = \n", dataframe.shape)
print("dimension \n", dataframe.ndim)
print("total elements \n", dataframe.size)
print("row index \n", dataframe.index)
print("list each elements \n", dataframe.values)
print("column index \n", dataframe.columns)

   Bob  Alice
0    1    5.0
1    2    6.0
2    3    7.0
3    6    NaN
shape = 
 (4, 2)
dimension 
 2
total elements 
 8
row index 
 RangeIndex(start=0, stop=4, step=1)
list each elements 
 [[ 1.  5.]
 [ 2.  6.]
 [ 3.  7.]
 [ 6. nan]]
column index 
 Index(['Bob', 'Alice'], dtype='object')
